### ISSUE TITLE
Support other locator types in ElementFactory

### ISSUE THREAD

**Issue by mialeska** [aquality-automation/aquality-selenium-core-java#32]
Currently only XPath locators for multiple elements are supported.
Although some locator types could be converted to XPath:
- By.name("awesome") -> By.xPath("//*[@name='awesome']") (please note that this is for web, e.g. for desktop xPath would be //*[@Name='awesome'] according to https://github.com/microsoft/WinAppDriver/blob/master/Docs/AuthoringTestScripts.md )
- By.id("awesome") -> By.xPath("//*[@id='awesome']") 
and so on

**Comment by DmitryBogatko** [comment]
decided that we do not need this feature in core
