### ISSUE TITLE
ConditionalWait.waitForTrue() methods throw checked exceptions

### ISSUE THREAD

**Issue by eugenenekh** [aquality-automation/aquality-selenium-core-java#53]
Is it possible for waitForTrue() methods to throw unchecked exceptions so we could avoid wrapping it with try/catch/throw a RuntimeException?

**Comment by mialeska** [comment]
@eugenenekh in this method we just throw standart `java.util.concurrent.TimeoutException`, which is checked exception in java. You could use `if (!waitFor(BooleanSupplier)) throw new YourOwnExcneption();` or use T waitFor(ExpectedCondition<T> condition) - it uses WebDriver's FluentWait inside and match it's behaviour: if T is not boolean and the value is not null, it throws `org.openqa.selenium.TimeoutException` which is unchecked in java.
